points:
    key.padding: cy
    zones:
        main:
            rows:
                bottom.row_net: P2
                home.row_net: P0
                top.row_net: P1
            columns:
                pinky:
                    key:
                        col_net: P7
                        spread: cx
                    rows:
                        bottom:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_pinky_home
                        home:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_pinky_top
                        top:
                            led_in: "rgb_{{name}}"
                ring:
                    key:
                        col_net: P6
                        stagger: 4
                        spread: cx
                    rows:
                        bottom:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_pinky_bottom
                        home:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_ring_bottom
                        top:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_ring_home
                middle:
                    key:
                        col_net: P5
                        stagger: 2
                        spread: cx
                    rows:
                        bottom:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_middle_home
                        home:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_middle_top
                        top:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_ring_top
                index:
                    key:
                        col_net: P4
                        stagger: -2
                        spread: cx
                    rows:
                        bottom:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_thumb_home_home
                        home:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_index_bottom
                        top:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_index_home
                inner:
                    key:
                        col_net: P3
                        stagger: -2
                        spread: cx
                    rows:
                        bottom:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_inner_home
                        home:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_inner_top
                        top:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_index_top
        thumb:
            anchor:
                ref: main_index_bottom
                shift: [-0.5cx, -cy]
            rows.home.row_net: P8
            columns:
                inner.key:
                    col_net: P5
                    led_in: "rgb_{{name}}"
                    led_out: rgb_main_middle_bottom
                    spread: cx
                home.key:
                    col_net: P4
                    led_in: "rgb_{{name}}"
                    led_out: rgb_thumb_inner_home
                    spread: cx + 2
                    rotate: -18
                    stagger: -3.2
                outer.key:
                    col_net: P3
                    led_in: P9
                    led_out: rgb_main_inner_bottom
                    spread: cx
                    rotate: -36
                    stagger: -9.2
outlines:
    _board_outline:
        -   what: polygon
            fillet: 2
            points:
                -   ref: thumb_outer_home
                    shift: [0.6cx, 0.6cy]
                -   ref: thumb_outer_home
                    shift: [0.6cx, -0.6cy]
                -   ref: thumb_outer_home
                    shift: [-0.4cx, -0.6cy]

                -   ref: thumb_home_home
                    shift: [0.4cx, -0.6cy]
                -   ref: thumb_home_home
                    shift: [-0.4cx, -0.6cy]

                -   ref: thumb_inner_home
                    shift: [0.4cx, -0.6cy]
                -   ref: thumb_inner_home
                    shift: [-0.6cx, -0.6cy]

                -   ref: main_pinky_bottom
                    shift: [1.6cx, -0.6cy]
                -   ref: main_pinky_bottom
                    shift: [0.6cx, -0.6cy]
                -   ref: main_pinky_bottom
                    shift: [-0.6cx, -0.6cy]

                -   ref: main_pinky_top
                    shift: [-0.6cx, 0.6cy]
                -   ref: main_pinky_top
                    shift: [0.4cx, 0.6cy]

                -   ref: main_ring_top
                    shift: [-0.5cx, 0.6cy]
                -   ref: main_ring_top
                    shift: [0.4cx, 0.6cy]

                -   ref: main_middle_top
                    shift: [-0.4cx, 0.61cy]
                -   ref: main_middle_top
                    shift: [0.4cx, 0.6cy]

                -   ref: main_index_top
                    shift: [-0.4cx, 0.6cy]
                -   ref: main_index_top
                    shift: [0.5cx, 0.6cy]

                -   ref: main_inner_top
                    shift: [-0.4cx, 0.6cy]
                -   ref: main_inner_top
                    shift: [0.5cx, 0.6cy]

                -   ref: main_inner_top
                    shift: [0.6cx, 0.4cy]
                -   ref: main_inner_top
                    shift: [1.8cx, 0.4cy]

                -   ref: main_inner_bottom
                    shift: [1.8cx, -0.6cy]
    _keycap_outlines:
        -   what: rectangle
            fillet: 2
            where: true
            size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
    preview:
        -   what: outline
            name: _board_outline
            operation: stack
        -   what: outline
            name: _keycap_outlines
            operation: stack
cases.josukey:
    -   what: outline
        name: _board_outline
        extrude: 3
        operation: subtract
    -   what: outline
        name: _keycap_outlines
        extrude: 6
        operation: add
pcbs.josukey:
    outlines:
        main.outline: _board_outline
        keycaps:
            outline: _keycap_outlines
            layer: Eco1.User
    footprints:
        led:
            what: sk6812mini
            where: true
            adjust:
                shift: [0, -5]
            params:
                din: "{{led_in}}"
                dout: "{{led_out}}"
                cutout: true
        diode:
            what: sod-123w
            where: true
            params:
                from: "{{name}}"
                to: "{{row_net}}"
            adjust:
                shift: [ -7.6, -1.6 ]
                rotate: 90
        choc:
            what: choc
            where: true
            params:
                keycaps: true
                reverse: true
                hotswap: true
                from: "{{col_net}}"
                to: "{{name}}"
        promicro:
            what: promicro_pretty
            where:
                ref: main_inner_home
            adjust:
                shift: [22, 6.5]
                rotate: -90
            # params:
            #     # left
            #     P1:  main_inner_top
            #     P0:  main_index_top
            #     # GND
            #     # GND
            #     P2:  main_middle_top
            #     P3:  main_ring_top
            #     P4:  main_pinky_top
            #     P5:  main_inner_home
            #     P6:  main_index_home
            #     P7:  main_middle_home
            #     P8:  main_ring_home
            #     P9:  main_pinky_home
            #     # right
            #     # RAW
            #     # GND
            #     # RST
            #     # VCC
            #     P21: thumb_outer_home
            #     P20: thumb_home_home
            #     P19: thumb_inner_home
            #     P18: main_pinky_bottom
            #     P15: main_ring_bottom
            #     P14: main_middle_bottom
            #     P16: main_index_bottom
            #     P10: main_inner_bottom
        jst-s2b-ph-kl:
            what: jst-s2b-ph-kl
            where:
                ref: main_inner_bottom
                shift: [21, -2]
                rotate: 180
            params:
                neg: GND
        pcm12:
            what: pcm12
            where:
                ref: main_inner_bottom
                shift: [30.5, 3]
                rotate: 90
            params:
                from: pos
                to: RAW
        wuerth-434121025816:
            what: wuerth-434121025816
            where:
                ref: main_inner_bottom
                shift: [30, -6]
                rotate: 90
            params:
                r1: RST
                r2: GND
        front_text: &text
            what: text
            where: &textWhere
                ref: main_pinky_bottom
                shift: [12, -7]
            params: &textParams
                text: Josukey\nA keyboard for Joey
                justify: left
        back_text:
            <<: *text
            where:
                <<: *textWhere
                shift: [27, -7]
            params:
                <<: *textParams
                layer: B.SilkS
                justify: left mirror
        safeText:
            <<: *text
            what: keepout
            params:
                points:
                    -   x: -0.5
                        y: -2
                    -   x: 15.5
                        y: -2
                    -   x: 15.5
                        y: 2
                    -   x: -0.5
                        y: 2
        peace: &icon
            what: peace
            where:
                ref: main_inner_bottom
                shift: [16, -9]
            params:
                scale: 1.25
        love:
            <<: *icon
            what: love
        safeIcon:
            <<: *icon
            what: keepout
            params:
                points:
                    -   x: 0
                        y: 0
                    -   x: 8
                        y: 0
                    -   x: 8
                        y: 8
                    -   x: 0
                        y: 8
