points:
    key.padding: cy
    zones:
        main:
            rotate: 28
            rows:
                bottom:
                home:
                top:
            columns:
                pinky:
                ring:
                    key:
                        splay: -8
                        spread: cx+4
                        stagger: 6
                middle:
                    key:
                        splay: -4
                        spread: cx+2
                        stagger: -1
                index:
                    key:
                        splay: -16
                        spread: cx+4
                        stagger: -4
                inner:
                    key:
                        spread: cx+2
                        stagger: -2
        thumb:
            anchor:
                ref: main_index_bottom
                shift: [0, -cy-8]
            rows.home:
            columns:
                inner:
                home:
                    key:
                        rotate: -16
                        spread: cx+4
                        stagger: -3
                outer.key:
                    rotate: -32
                    spread: cx+2
                    stagger: -9
outlines:
    _board_outline:
        -   what: polygon
            fillet: 2
            points:
                -   ref: thumb_outer_home
                    shift: [0.6cx, 0.6cy]
                -   ref: thumb_outer_home
                    shift: [0.6cx, -0.6cy]
                -   ref: thumb_home_home
                    shift: [0.6cx, -0.6cy]
                -   ref: thumb_home_home
                    shift: [-0.6cx, -0.6cy]
                -   ref: thumb_inner_home
                    shift: [-0.6cx, -0.6cy]
                -   ref: thumb_inner_home
                    shift: [-0.6cx, 0.6cy]
                -   ref: main_middle_bottom
                    shift: [0.4cx, -0.7cy]
                -   ref: main_pinky_bottom
                    shift: [0.6cx, -0.6cy]
                -   ref: main_pinky_bottom
                    shift: [-0.6cx, -0.6cy]
                -   ref: main_pinky_top
                    shift: [-0.6cx, 0.6cy]
                -   ref: main_ring_top
                    shift: [-0.6cx, 0.6cy]
                -   ref: main_middle_top
                    shift: [-0.6cx, 0.6cy]
                -   ref: main_middle_top
                    shift: [0.6cx, 0.6cy]
                -   ref: main_index_top
                    shift: [-0.6cx, 0.6cy]
                -   ref: main_index_top
                    shift: [0.6cx, 0.6cy]
                -   ref: main_inner_top
                    shift: [0.6cx, 0.6cy]
                -   ref: main_inner_top
                    shift: [1cx, 0.4cy]
                -   ref: main_inner_top
                    shift: [1.6cx, 0cy]
                -   ref: main_inner_top
                    shift: [1.8cx, -0.2cy]
                -   ref: main_inner_top
                    shift: [2cx, -0.4cy]
                -   ref: main_inner_top
                    shift: [2.2cx, -0.7cy]
                -   ref: main_inner_top
                    shift: [2.4cx, -1cy]
    _keycap_outlines:
        -   what: rectangle
            fillet: 2
            where: true
            size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
    preview:
        -   what: outline
            name: _board_outline
            operation: stack
        -   what: outline
            name: _keycap_outlines
            operation: stack

pcbs.josukey:
    outlines:
        main.outline: _board_outline
        keycaps:
            outline: _keycap_outlines
            layer: Eco1.User
    footprints:
        choc:
            what: choc
            where: true
            adjust:
                rotate: 180
            params:
                designator: S
                keycaps: true
                reverse: true
                from: "{{name}}"
                to: GND
        choc_hotswap:
            what: choc
            where: true
            params:
                designator: S
                keycaps: true
                reverse: true
                hotswap: true
                from: "{{name}}"
                to: GND
        promicro:
            what: promicro_pretty
            where:
                ref: main_inner_home
            adjust:
                shift: [22, -1]
                rotate: -90
            params:
                # left
                P1:  main_inner_top
                P0:  main_index_top
                # GND
                # GND
                P2:  main_middle_top
                P3:  main_ring_top
                P4:  main_pinky_top
                P5:  main_inner_home
                P6:  main_index_home
                P7:  main_middle_home
                P8:  main_ring_home
                P9:  main_pinky_home
                # right
                # RAW
                # GND
                # RST
                # VCC
                P21: thumb_outer_home
                P20: thumb_home_home
                P19: thumb_inner_home
                P18: main_pinky_bottom
                P15: main_ring_bottom
                P14: main_middle_bottom
                P16: main_index_bottom
                P10: main_inner_bottom
        bat:
            what: bat
            where:
                ref: main_inner_bottom
                shift: [22, -4]
                rotate: -90
            params:
                neg: GND
        pcm12:
            what: pcm12
            where:
                ref: main_inner_home
                shift: [40.6, -4]
                rotate: 82.2
            params:
                reverse: true
                from: pos
                to: RAW
        wuerth_434121025816:
            what: wuerth_434121025816
            where:
                ref: main_inner_bottom
                shift: [38.5, 2.5]
                rotate: 82.2
            params:
                reverse: true
                r1: RST
                r2: GND
        via_pos:
            what: via
            where:
                ref: main_inner_bottom
                shift: [35.5, 14]
            params:
                net: pos
        via_raw:
            what: via
            where:
                ref: main_inner_bottom
                shift: [36.5, 14]
            params:
                net: RAW
        via_gnd:
            what: via
            where:
                ref: main_inner_bottom
                shift: [35, 8.3]
            params:
                net: GND
        via_rst:
            what: via
            where:
                ref: main_inner_bottom
                shift: [36, 8.3]
            params:
                net: RST
        front_text: &text
            what: text
            where: &textWhere
                ref: main_pinky_bottom
                shift: [12, -7]
            params: &textParams
                text: Josukey\nA keyboard for Joey
                justify: left
        back_text:
            <<: *text
            where:
                <<: *textWhere
                shift: [27, -7]
            params:
                <<: *textParams
                layer: B.SilkS
                justify: left mirror
        peace: &icon
            what: peace
            where:
                ref: main_inner_bottom
                shift: [25, -10]
            params:
                scale: 2
        love:
            <<: *icon
            what: love
