meta:
  engine: 4.1.0
  version: 0.0.1
  author: auryn

units: 
  kx: u
  ky: u
  px: u + 2
  py: u + 2

points:
    key.padding: ky
    zones:
        main:
            rows:
                bottom.row_net: P2
                home.row_net: P0
                top.row_net: P1
            columns:
                pinky:
                    key:
                        col_net: P7
                        spread: kx
                ring:
                    key:
                        col_net: P6
                        stagger: 0.4 ky
                        spread: kx
                middle:
                    key:
                        col_net: P5
                        stagger: 0.28 ky
                        spread: kx
                index:
                    key:
                        col_net: P4
                        stagger: -0.33 ky
                        spread: kx
                inner:
                    key:
                        col_net: P3
                        stagger: -0.11 ky 
                        spread: kx
        thumb:
            anchor:
                ref: main_inner_bottom
                shift: [-1 kx, -1.15 ky]
            rows.home.row_net: P8
            columns:
                inner.key:
                    origin: [-1 kx, -1.15 ky]
                    col_net: P5
                    spread: kx
                home.key:
                    col_net: P4
                    splay: -0.5 ky
                    origin: [-0.5 kx, -0.15 ky]
                    spread: 1.2 kx
                outer.key:
                    col_net: P3
                    spread: 1.2 kx
                    splay: -0.5 ky 
                    origin: [-0.8 kx, -0.15 ky]
outlines:
    _board_outline:
        -   what: polygon
            fillet: 2
            points:
                -   ref: thumb_outer_home
                    shift: [0.6kx, 0.6ky]
                -   ref: thumb_outer_home
                    shift: [0.6kx, -0.6ky]
                -   ref: thumb_outer_home
                    shift: [-0.4kx, -0.6ky]

                -   ref: thumb_home_home
                    shift: [0.4kx, -0.6ky]
                -   ref: thumb_home_home
                    shift: [-0.4kx, -0.6ky]

                -   ref: thumb_inner_home
                    shift: [0.4kx, -0.6ky]
                -   ref: thumb_inner_home
                    shift: [-0.6kx, -0.6ky]

                -   ref: main_pinky_bottom
                    shift: [1.6kx, -0.6ky]
                -   ref: main_pinky_bottom
                    shift: [0.6kx, -0.6ky]
                -   ref: main_pinky_bottom
                    shift: [-0.6kx, -0.6ky]

                -   ref: main_pinky_top
                    shift: [-0.6kx, 0.6ky]
                -   ref: main_pinky_top
                    shift: [0.4kx, 0.6ky]

                -   ref: main_ring_top
                    shift: [-0.6kx, 0.6ky]
                -   ref: main_ring_top
                    shift: [0.4kx, 0.6ky]

                -   ref: main_middle_top
                    shift: [-0.6kx, 0.6ky]
                -   ref: main_middle_top
                    shift: [0.6kx, 0.6ky]

                -   ref: main_index_top
                    shift: [-0.4kx, 0.6ky]
                -   ref: main_index_top
                    shift: [0.5kx, 0.6ky]

                -   ref: main_inner_top
                    shift: [-0.4kx, 0.6ky]
                -   ref: main_inner_top
                    shift: [0.5kx, 0.6ky]

                -   ref: main_inner_top
                    shift: [0.6kx, 0.4ky]
                -   ref: main_inner_top
                    shift: [1.8kx, 0.4ky]

                -   ref: main_inner_bottom
                    shift: [1.8kx, -0.6ky]
    _keycap_outlines:
        -   what: rectangle
            fillet: 2
            where: true
            size: [1kx , 1ky ] # Choc keycaps are 17.5 x 16.5
    preview:
        -   what: outline
            name: _board_outline
            operation: stack
        -   what: outline
            name: _keycap_outlines
            operation: stack
cases.avocado:
    -   what: outline
        name: _board_outline
        extrude: 3
        operation: subtract
    -   what: outline
        name: _keycap_outlines
        extrude: 6
        operation: add
pcbs.avocado:
    outlines:
        main.outline: _board_outline
        keycaps:
            outline: _keycap_outlines
            layer: Eco1.User
    footprints:
        diode:
            what: sod-123w
            where: true
            params:
                from: "{{row_net}}"
                to: "{{row_net}}"
            adjust:
                shift: [ -7.6, -1.6 ]
                rotate: 90
        mx:
            what: mx
            where: true
            params:
                keycaps: true
                reverse: true
                hotswap: true
                from: "{{col_net}}"
                to: "{{row_net}}"
        promicro:
            what: promicro_pretty
            where:
                ref: 
                  - main_inner_home
                shift: [22, 6.5]
            params:
              reversable_pins: 12
                # rotate: -90
        jst-s2b-ph-kl:
            what: jst-s2b-ph-kl
            where:
                ref:
                  - main_inner_bottom
                shift: [21, -2]
                rotate: 180
            params:
                neg: GND
        pcm12:
            what: pcm12
            where:
                ref: 
                  - main_inner_bottom
                shift: [30.5, 3]
                rotate: 90
            params:
                from: pos
                to: RAW
        wuerth-434121025816:
            what: wuerth-434121025816
            where:
                ref: 
                  - main_inner_bottom
                shift: [30, -6]
                rotate: 90
            params:
                r1: RST
                r2: GND
        front_text: &text
            what: text
            where: &textWhere
                ref: 
                  - main_pinky_bottom
                shift: [12, -7]
            params: &textParams
                text: Avocado\nA keyboard from Auryn
                justify: left
        back_text:
            <<: *text
            where:
                <<: *textWhere
                shift: [27, -7]
            params:
                <<: *textParams
                layer: B.SilkS
                justify: left mirror
        avocado:
           where:
             ref: main_middle_bottom
             shift: [-5, -15]
           what: avocado
