meta:
  engine: 4.1.0
  version: 0.0.1
  author: auryn
points:
    key.padding: cy
    zones:
        main:
            rows:
                bottom.row_net: P2
                home.row_net: P0
                top.row_net: P1
            columns:
                pinky:
                    key:
                        col_net: P7
                        spread: cx
                ring:
                    key:
                        col_net: P6
                        stagger: 0.4 cy
                        spread: cx
                middle:
                    key:
                        col_net: P5
                        stagger: 0.28 cy
                        spread: cx
                index:
                    key:
                        col_net: P4
                        stagger: -0.33 cy
                        spread: cx
                inner:
                    key:
                        col_net: P3
                        stagger: -0.11 cy 
                        spread: cx
        thumb:
            anchor:
                ref: main_inner_bottom
                shift: [-1 cx, -1.15 cy]
            rows.home.row_net: P8
            columns:
                inner.key:
                    origin: [-1 cx, -1.15 cy]
                    col_net: P5
                    spread: cx
                home.key:
                    col_net: P4
                    splay: -0.5 cy
                    origin: [-0.5 cx, -0.15 cy]
                    spread: 1.2 cx
                outer.key:
                    col_net: P3
                    spread: 1.2 cx
                    splay: -0.5 cy 
                    origin: [-0.8 cx, -0.15 cy]
outlines:
    _board_outline:
        -   what: polygon
            fillet: 2
            points:
                -   ref: thumb_outer_home
                    shift: [0.6cx, 0.6cy]
                -   ref: thumb_outer_home
                    shift: [0.6cx, -0.6cy]
                -   ref: thumb_outer_home
                    shift: [-0.4cx, -0.6cy]

                -   ref: thumb_home_home
                    shift: [0.4cx, -0.6cy]
                -   ref: thumb_home_home
                    shift: [-0.4cx, -0.6cy]

                -   ref: thumb_inner_home
                    shift: [0.4cx, -0.6cy]
                -   ref: thumb_inner_home
                    shift: [-0.6cx, -0.6cy]

                -   ref: main_pinky_bottom
                    shift: [1.6cx, -0.6cy]
                -   ref: main_pinky_bottom
                    shift: [0.6cx, -0.6cy]
                -   ref: main_pinky_bottom
                    shift: [-0.6cx, -0.6cy]

                -   ref: main_pinky_top
                    shift: [-0.6cx, 0.6cy]
                -   ref: main_pinky_top
                    shift: [0.4cx, 0.6cy]

                -   ref: main_ring_top
                    shift: [-0.5cx, 0.6cy]
                -   ref: main_ring_top
                    shift: [0.4cx, 0.6cy]

                -   ref: main_middle_top
                    shift: [-0.4cx, 0.61cy]
                -   ref: main_middle_top
                    shift: [0.4cx, 0.6cy]

                -   ref: main_index_top
                    shift: [-0.4cx, 0.6cy]
                -   ref: main_index_top
                    shift: [0.5cx, 0.6cy]

                -   ref: main_inner_top
                    shift: [-0.4cx, 0.6cy]
                -   ref: main_inner_top
                    shift: [0.5cx, 0.6cy]

                -   ref: main_inner_top
                    shift: [0.6cx, 0.4cy]
                -   ref: main_inner_top
                    shift: [1.8cx, 0.4cy]

                -   ref: main_inner_bottom
                    shift: [1.8cx, -0.6cy]
    _keycap_outlines:
        -   what: rectangle
            fillet: 2
            where: true
            size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
    preview:
        -   what: outline
            name: _board_outline
            operation: stack
        -   what: outline
            name: _keycap_outlines
            operation: stack
cases.avocado:
    -   what: outline
        name: _board_outline
        extrude: 3
        operation: subtract
    -   what: outline
        name: _keycap_outlines
        extrude: 6
        operation: add
pcbs.avocado:
    outlines:
        main.outline: _board_outline
        keycaps:
            outline: _keycap_outlines
            layer: Eco1.User
    footprints:
        diode:
            what: sod-123w
            where: true
            params:
                from: "{{name}}"
                to: "{{row_net}}"
            adjust:
                shift: [ -7.6, -1.6 ]
                rotate: 90
        choc:
            what: choc
            where: true
            params:
                keycaps: true
                reverse: true
                hotswap: true
                from: "{{col_net}}"
                to: "{{name}}"
        promicro:
            what: pro_micro_pretty
            where:
                ref: 
                  - main_inner_home
                shift: [22, 6.5]
            params:
              reversable_pins: 12
                # rotate: -90
        jst-s2b-ph-kl:
            what: jst-s2b-ph-kl
            where:
                ref:
                  - main_inner_bottom
                shift: [21, -2]
                rotate: 180
            params:
                neg: GND
        pcm12:
            what: pcm12
            where:
                ref: 
                  - main_inner_bottom
                shift: [30.5, 3]
                rotate: 90
            params:
                from: pos
                to: RAW
        wuerth-434121025816:
            what: wuerth-434121025816
            where:
                ref: 
                  - main_inner_bottom
                shift: [30, -6]
                rotate: 90
            params:
                r1: RST
                r2: GND
        front_text: &text
            what: text
            where: &textWhere
                ref: 
                  - main_pinky_bottom
                shift: [12, -7]
            params: &textParams
                text: Avocado\nA keyboard from Auryn
                justify: left
        back_text:
            <<: *text
            where:
                <<: *textWhere
                shift: [27, -7]
            params:
                <<: *textParams
                layer: B.SilkS
                justify: left mirror
        love:
            where:
              ref: main_inner_bottom
              shift: [0, 0]
            what: love
