on: [push, pull_request, workflow_dispatch]
  workflow_dispatch:
    inputs:
      build_matrix_path: 'path to zmk build'
      required: true
      default: zmk/build.yaml
    

# env:
#   build_matrix: zmk/build.yaml


jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
