on: [push, pull_request, workflow_dispatch]

env:
  build_matrix: zmk/build.yaml
inputs:
  build_matrix_path: zmk/

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
